
<script type="text/javascript">
function GetClock(){
var d=new Date();
var nday=d.getDay(),nmonth=d.getMonth(),ndate=d.getDate(),nyear=d.getYear(),nhour=d.getHours(),nmin=d.getMinutes(),nsec=d.getSeconds(),ap;

     if(nhour==0){ap=" AM";nhour=12;}
else if(nhour<12){ap=" AM";}
else if(nhour==12){ap=" PM";}
else if(nhour>12){ap=" PM";nhour-=12;}

if(nyear<1000) nyear+=1900;
if(nmin<=9) nmin="0"+nmin;
if(nsec<=9) nsec="0"+nsec;

document.getElementById('clockbox').innerHTML=""+(nmonth+1)+"/"+ndate+"/"+nyear+" "+nhour+":"+nmin+":"+nsec+ap+"";
}

window.onload=function(){
GetClock();
setInterval(GetClock,1000);
}
</script>
<div style="margin-left: 80%;font-size: 20px;border: 3px solid red;padding: 13px;width:15%;margin-top: -1%;  " id="clockbox"></div>

<div class="container" style="width:60%;">
    <div  class="heading"  style="border:2px solid black ;border-bottom:0px solid white;">
         
        
        <div class="col">Order Date</div>
         <div class="col">User Name</div>
		 <div class="col">Order Room </div>
         <div class="col">Ext.  </div>
         <div class="col">Action </div>
         
    </div>

                            <?php
                         
for ($i = 0; $i < count($this->orders); $i++) {
    ?>
 

    <div  class="heading2"  style="border:2px solid black ;"  >
        
        <div class="col"><?php echo  $this->orders[$i]['order_date_time'];?></div>
        <div class="col"><?php echo  $this->orders[$i]['user_name'];?></div>
          <div class="col"><?php echo  $this->orders[$i]['user_room'];?></div>
	   <div class="col"><?php echo  $this->orders[$i]['user_ext'];?></div>
           <div class="col"><a href="<?php echo $this->baseUrl() ; ?>/index/update?id=<?php echo $this->orders[$i]['order_id']; ?>" >Deliver</a></div>
         
    </div>
<span style="width:5px;"  data-toggle="collapse" id="get" value="<?php echo  $this->orders[$i]['order_id'];?>" data-target="#<?php echo  $this->orders[$i]['order_id'];?>" class="icon-plus"></span>
                                  
	
    	<div class="accordion-body   collapse " id="<?php echo  $this->orders[$i]['order_id'];?>"style="border:2px solid black;width:150%;margin-left: 5%;">
                           
   

   
         <div class="col"><?php echo  $this->orders[$i]['total_price'];?></div>
                        </div>


	<?php } ?>
    </div>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/jquery-1.7.2.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/excanvas.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/chart.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/bootstrap.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/base.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/dt.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/int.js"></script>
<script>
 $(function () {
        $(document).on('click', '#get', function () {
            $(this).toggleClass("icon-minus");
            var id =$(this).attr("value");
         
               $.ajax({
                    type: "GET",
                    url: "<?php echo $this->baseUrl(); ?>/index/index",
                    data: 'id=' + id,
                    success: function (msg)
                    {
                        $("#"+id).empty();
                       $("#"+id).append(msg);
                      
                    }
                });
    });
     });
</script>
<style type="text/css">
*{ padding:0px; 
   margin:0px; }
.accordion-heading { background-color:white; color: black; }

.accordion-heading:hover { background-color:#4b77be; color:black;
  -webkit-transition: all 0.5s ease-in-out;
     -moz-transition: all 0.5s ease-in-out;
       -o-transition: all 0.5s ease-in-out;
          transition: all 0.5s ease-in-out; }
          
.accordion-heading  { color:black; 
border-collapse: collapse;
   text-decoration:none; 
   text-transform:uppercase; }
   .container{
    display:table;
    width:90%;
    height:100%;
    border-collapse: collapse;
     cursor: pointer;
    }
 .heading{
     font-weight: bold;
     display:table-row;
     background-color:#CBCBDB;
     text-align: center;
     line-height: 25px;
     font-size: 14px;
     font-family:georgia;
     color:black;
    
     
 }
  .heading2{
     font-weight: bold;
     display:table-row;
     background-color:#EEEEF7;
     text-align: center;
     line-height: 25px;
     font-size: 14px;
     font-family:georgia;
     color:black;
    
     
 }
  .heading1{
     font-weight: bold;
     display:table-row;
     background-color:#3f4b5a;
     text-align: center;
     line-height: 25px;
     font-size: 14px;
     font-family:georgia;
     color:#fff;
     
 }
 .table-row{  
     display:table-row;
     text-align: center;
     height:30px;
     border: 2px solid white;
     border-bottom: 2px solid grey;
 }
  .table-row1{  
     display:table-row;
     text-align: center;
     height:30px;
     border: 2px solid #E64D23;
 }
 .col{ 
	display:table-cell;
    padding: 10px;
 	
 }
</style>

          