    <link href="<?php echo $this->baseUrl(); ?>/assets/css/smooth.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl(); ?>/assets/css/int.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl(); ?>/assets/css/pages/signin.css" rel="stylesheet" type="text/css">
  <style>
      #close{
        background-image: url("<?php echo $this->baseUrl() ; ?>/assets/img/close.png");
      }
  </style>
<div class="main" >
     
    <span><h1 style="margin-left:10%; ">All Users</h1><?php echo $this->error ;?></span>
    <span><a href="#large"  data-toggle="modal" id="modal" style="text-decoration: underline;position: absolute;margin-left: 80%;margin-top: -1.5%;color:blue;font-weight: bold;" ><i class="icon-plus"></i>Add New User</a></span>
	<div class="main-inner" style="width:80%;margin-left:10%;">
	<table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Room</th>
                <th>Image</th>
                <th>Ext</th>
		<th>Action</th>
                <th>Age</th>
           
            </tr>
        </thead>
 
      
<?php
for ($i = 0; $i < count($this->users); $i++) {
    ?>

                            <tr >
                                <td >
    <?php echo $this->users[$i]['user_name']; ?>
                                </td>
                                  <td class="center">
    <?php echo $this->users[$i]['user_room']; ?>
                                </td>
                              
                                <td class="center">
                                    <img width="70px" height="50px" class="img-circle" src="<?php echo $this->baseUrl(); ?>/assets/img/users/<?php echo $this->users[$i]['user_img']; ?>"/> 
                                </td>
                                  <td>
                               <?php echo $this->users[$i]['user_ext']; ?>     
                                    
                                </td>
                                   <td style="padding-left:70px;">
                                   
                                     <a href="#update" data-toggle="modal" id="<?php echo $this->users[$i]['user_id']; ?>" class="updatebutton"> <img src="<?php echo $this->baseUrl(); ?>/assets/img/icn_edit.png"/></a>
                                    / &nbsp;
                                    <a href="#" id="<?php echo $this->users[$i]['user_id']; ?>" class="delbutton" ><img src="<?php echo $this->baseUrl(); ?>/assets/img/icn_trash.png"/></a>
                                </td>   
                              
                               
                                   <td></td>
                                                           
                            </tr>
<?php } ?>                                                        
                    </tbody>

    </table>

	    
	    
	</div> <!-- /main-inner -->
        
      
</div> <!-- /main -->
    
<!-- /.modal -->
<div class="modal fade bs-modal-lg" id="large" tabindex="-1" role="dialog" aria-hidden="true">
   
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                     <button  data-dismiss="modal" aria-hidden="true" style=" box-shadow: 5px 5px 5px #888888;float: right;" >Close</button>
                    <h4 class="modal-title">Add New Product </h4>

                </div>
                
                 

                <div style="margin-left:3%;">
	
	
                    <form  style="display: none;" id="addform"  role="form" enctype="multipart/form-data" method="post"  action="<?php echo $this->baseUrl(); ?>/users/add" class="form-horizontal">

		
					
			
                            
                    <br/>
				
				<div class="field">
                                    <span style="color:black;" for="user_name">Name:</span>
					<input type="text" id="firstname" name="user_name"  value="" placeholder="user Name" class="login" />
				</div> <!-- /field -->
				<br/>
				<div class="field">
					<span style="color:black;" for="user_email">Email:</span>	
                                        <input type="email" id="lastname" name="user_email" value=""  class="login" />
				</div> <!-- /field -->
				<br/>
				
		
				<br/>
				<div class="field">
					<span style="color:black;" for="password">Password:</span>
				<input type="text" id="lastname" name="user_password" value=""  class="login" />
                                </div> <!-- /field -->
                                <br/>
				<div class="field">
					<span style="color:black;" for="con_password">Con_Password:</span>
				<input type="text" id="lastname" name="con_password" value=""  class="login" />
                                </div> <!-- /field -->
                                <br/>
				<div class="field">
					<span style="color:black;" for="user_room">Room No:</span>
				<input type="text" id="lastname" name="user_room" value=""  class="login" />
                                </div> <!-- /field -->
				<br/>
				<div class="field">
					<span style="color:black;" for="user_ext">Ext:</span>
				<input type="text" id="lastname" name="user_ext" value=""  class="login" />
                                </div> <!-- /field -->
                                <br/>
				<div class="field">
					<span style="color:black;" for="file">Profile Pic:</span>
				<input type="file" name="file"/>
                                </div> <!-- /field -->
                                
				
                                <hr>
                                <div class="login-actions" style="margin-top: -2%;">
				<input class="button" type="reset"   style="margin-right:30%; box-shadow: 5px 5px 5px #888888;" value="Reset" />				
                                <input class="button" type="submit" style="margin-right:10%; box-shadow: 5px 5px 5px #888888;" vlaue="Save"/>
				
			</div> <!-- .actions -->
			
		</form>
		

</div> <!-- /account-container -->


             
            </div>

            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<!-- /.modal -->
<div class="modal fade bs-modal-lg" id="update" tabindex="-1" role="dialog" aria-hidden="true">
   
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="close" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Update User </h4>

                </div>
                
                 

                <div style="margin-left:3%;">
	
	
		 <form   role="form" enctype="multipart/form-data" method="post" id="fm1" action="<?php echo $this->baseUrl(); ?>/users/update" class="form-horizontal">

		
			
		</form>
		

</div> <!-- /account-container -->


             
            </div>

            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
    


    

<script src="<?php echo $this->baseUrl(); ?>/assets/js/jquery-1.7.2.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/excanvas.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/chart.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/bootstrap.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/base.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/dt.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/int.js"></script>
<script>
$(document).ready(function() {
    $('#example').dataTable( {
        "columnDefs": [
           
            {
                "targets": [ 5 ],
                "visible": false
            }
        ]
    } );
} );
</script>
<script type="text/javascript">
    $(function () {
        $(document).on('click', '.delbutton', function () {
//Save the link in a variable called element
            var element = $(this);
//Find the id of the link that was clicked
            var del_id = element.attr("id");
//Built a url to send
            var info = 'id=' + del_id;
            if (confirm("are you sure to delete this Product !?"))
            {
                $.ajax({
                    type: "GET",
                    url: "<?php echo $this->baseUrl(); ?>/users/deluser",
                    data: 'id=' + del_id,
                    success: function ()
                    {
                        window.location = "<?php echo $this->baseUrl(); ?>/users";
                    }
                });
            }
            return false;
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        $(document).on('click', '.updatebutton', function () {
//Save the link in a variable called element
            var element = $(this);
//Find the id of the link that was clicked
            var del_id = element.attr("id");
//Built a url to send
            var info = 'id=' + del_id;
       
                $.ajax({
                    type: "GET",
                    url: "<?php echo $this->baseUrl(); ?>/users/edit",
                    data: 'id=' + del_id,
                    success: function (msg)
                    {
                        
                       $("#fm1").empty();
                        $("#fm1").append(msg);
                    }
                });
         
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        $(document).on('click', '#modal', function () {
                $("#addform").css("display","block");
        });
    });
</script>