<link href="<?php echo $this->baseUrl(); ?>/assets/css/smooth.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl(); ?>/assets/css/int.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl(); ?>/assets/css/datepicker.css" rel="stylesheet" type="text/css">
<style>
    .hiddenRow {
    padding: 0 !important;
}
    #close{
        background-image: url("<?php echo $this->baseUrl(); ?>/assets/img/close.png");
    }
</style>
<div style="margin-left: 20%;">
    from Date :
<input type="date" class="form-control" name="date" id="date1">
    to Date:
<input type="date" class="form-control" name="date" id="date2">
<input type="button" value="Find" id="find_date" />

     
    </div>


<div class="main" style="width:50%;margin-left:20%;" >
   <table class="table" style="border-collapse:collapse;">
    <thead>
        <tr style="background-color: #21a9ec;" id="trtr">
             <th>open</th>
            <th>Name</th>
            <th>Total Mount</th>
           
        </tr>
    </thead>
    <tbody id="tb_body">
        <?php  for ($i = 0; $i < count($this->users); $i++) { ?>
 
        <tr   style="color:blue;"   >
          
            <td  id="show"   data-toggle="collapse" value="<?php echo $this->users[$i]['user_id'] ?>" data-target="#<?php echo $this->users[$i]['user_id'] ?>" ><i id="plus" class="icon-plus"></i></td>
            <td><?php echo $this->users[$i]['user_name'] ?></td>
            <td class="text-success">$<?php echo $this->users[$i]['user_name'] ?></td>
          
        </tr>
    
                       
        <tr >
            <td colspan="6" class="hiddenRow"><div class="accordian-body collapse" id="<?php echo $this->users[$i]['user_id'] ?>"> 
                
                 <table class="table" style="border-collapse:collapse;" border="2px solid black">
    <thead>
        <tr>
            <th>open</th>
            <th>Order Date</th>
             <th>Status</th>
            <th>Amount</th>
            <th>Action</th>
           
        </tr>
    </thead>
    <tbody id="fill<?php echo $this->users[$i]['user_id'] ?>">
      
    </tbody>
                 </table>
                
                </div> </td>
        </tr>
      
       <?php } ?>
       
    </tbody>
</table> 
    

    
</div>






<script src="<?php echo $this->baseUrl(); ?>/assets/js/jquery-1.7.2.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/bootstrap-datepicker.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/chart.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/bootstrap.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/base.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/dt.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/js/int.js"></script>


<script>
    $(document).ready(function () {
        $('#example').dataTable({
            "columnDefs": [
                {
                    "targets": [4],
                    "visible": false
                },
                {
                    "targets": [5],
                    "visible": false
                }
            ]
        });
    });
</script>
<script type="text/javascript">
    $(function () {
       
        $(document).on('change', '#se', function () {
           
            
              var user_id = $(this).attr("value");
             
            $.ajax({
                type: "GET",
                url: "<?php echo $this->baseUrl(); ?>/myorders/getorderbyuser",
                data: 'id=' + user_id,
                success: function (msg)
                {
                    $("#tb_body").html(msg);
                }
            });

        });
    });
</script>


<script type="text/javascript">
    $(function () {
        $('.datepicker').datepicker();
        $(document).on('click', '#showorder', function () {
            $(this).find("#plus").toggleClass("icon-minus");
              var order_id = $(this).attr("value");
              
            $.ajax({
                type: "GET",
                url: "<?php echo $this->baseUrl(); ?>/myorders/getorder",
                data: 'id=' + order_id,
                success: function (msg)
                {

                    $("#fill"+order_id).html(msg);
                }
            });

        });
    });
</script>

<script type="text/javascript">
    $(function () {
        $(document).on('click', '#show', function () {
          $(this).find("#plus").toggleClass("icon-minus");
           var user_id = $(this).attr("value");
          
            $.ajax({
                type: "GET",
                url: "<?php echo $this->baseUrl(); ?>/myorders/getallorderdate",
                data: 'id=' + user_id,
                success: function (msg)
                {

                    $("#fill"+user_id).html(msg);
                }
            });

        });
    });
</script>

<script type="text/javascript">
    $(function () {
       $(document).on('click', '#find_date', function () {
        
           var from = $("#date1").val();
           var to = $("#date2").val();
         
          
            $.ajax({
                type: "GET",
                url: "<?php echo $this->baseUrl(); ?>/myorders/getbydate",
                data: {from:from,to:to},
                success: function (msg)
                {
                   $("#trtr").html("<th>open</th><th>Order Date</th> <th>Status</th> <th>Amount</th> <th>Action</th>");
                 $("#tb_body").html(msg);
                }
            });

        });
    });
</script>
