<!-- BEGIN PAGE LEVEL STYLES -->

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/assets/global/plugins/select2/select2.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css"/>
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            <?php
            if (isset($_GET['lang'])) {
                ?>
                <?php echo $pro_table ?> 
            <?php } else {
                ?>
                Product Views <small>managed product show</small>
            <?php } ?>

        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="index.html">Home</a>
                <?php
                if (isset($_GET['lang'])) {
                    ?>
                    <i class="fa fa-angle-left"></i>
                <?php } else {
                    ?>
                    <i class="fa fa-angle-right"></i> 
                <?php } ?>
            </li>
            <li>
                <a href="#">Products</a>
<?php
if (isset($_GET['lang'])) {
    ?>
                    <i class="fa fa-angle-left"></i>
                <?php } else {
                    ?>
                    <i class="fa fa-angle-right"></i> 
                <?php } ?>
            </li>
            <li>
                <a href="#">Product Views</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
        
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->


<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue-steel">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Product Update
                </div>

            </div>
        
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
       

        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                   
                    <h4 class="modal-title">Update Product </h4>

                </div>
                 <form   role="form" enctype="multipart/form-data" method="post" id="" action="<?php echo $this->baseUrl(); ?>/product/add" class="form-horizontal">
               <?php    for ($i = 0; $i < count($this->products); $i++) {
    ?>
                     <div class="form-body">

                        <div class="form-group">
                            <label class="control-label col-md-3">Product Name <span class="required">
                                    * </span>
                            </label>
                            <div class="col-md-4">
                                <input value=" <?php echo $this->products[$i]['pro_name']; ?>" type="text" name="pro_name" data-required="1" class="form-control" required/>
                            </div>
                        </div>
                          <div class="form-group">
                            <label class="control-label col-md-3">Product Quantity <span class="required">
                                    * </span>
                            </label>
                            <div class="col-md-4">
                                <input type="text" value=" <?php echo $this->products[$i]['pro_quantity']; ?>" name="pro_quantity" data-required="1" class="form-control" required/>
                            </div>
                        </div>
                     
                        <div class="form-group" style="margin-left: 22%;">
                            <label class="control-label ">Price <span class="required">
                                    *&nbsp;</span>
                                <div class="input-inline input-medium">
                                    <input id="touchspin_demo1" type="text" class=" blue-steel" value=" <?php echo $this->products[$i]['pro_price']; ?>" name="pro_price" class="form-control ">
                                </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Description&nbsp;&nbsp;</label>
                            <div class="col-md-4">
                                <textarea name="pro_desc" style="height:80px;" type="text" class="form-control"></textarea>
                                <span class="help-block">
                                    optional field </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Category <span class="required">
                                    * </span>
                            </label>
                            <div class="col-md-4">
                                <select style="color: #95a5a6;" class="form-control" name="cat_id" id="list-select">
                                    <option id="cat_id" value="-1">Choose Category</option>

<?php
for ($i = 0; $i < count($this->categorys); $i++) {
    
    echo'<option style="color:#95a5a6"   id="cat_id" value="' .$this->categorys[$i]['cat_id'].'">'.$this->categorys[$i]['cat_name'].'</option>';
}
?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Sub Category <span class="required">
                                    * </span>
                            </label>
                            <div class="col-md-4">
                                <select  style="color: #95a5a6;" class="form-control" name="sub_cat_id" id="list-target">

                                </select>
                            </div>
                        </div>
                        <div class="form-group" style="margin-left: 30%;">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
                                </div>
                                <div>
                                    <span class="btn default btn-file">
                                        <span class="fileinput-new">
                                            Select image </span>
                                        <span class="fileinput-exists">
                                            Change </span>
                                        <input type="file" name="file"/>
                                    </span>
                                    <a href="#" class="btn blue-steel fileinput-exists" data-dismiss="fileinput">
                                        Remove </a>
                                </div>
                            </div>
                        </div>
                        <div style="margin-top: -5px;margin-left: 40%;">     
                            <button  type="reset"  data-dismiss="modal"  class="btn blue-steel ">Cancel</button>
                            <input name="Add" type="submit" class="btn blue-steel"/>


                        </div>
                        <input type="hidden " style="margin-top: 10px; border: hidden;"/>
                    </div>


                </form>
                <?php } ?>
    </div>
</div>


        </div>
        <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- END PAGE CONTENT-->

<!-- END CONTENT -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="../../assets/global/plugins/respond.min.js"></script>
<script src="../../assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $this->baseUrl(); ?>/assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/admin/pages/scripts/table-editable.js"></script>

<script src="<?php echo $this->baseUrl(); ?>/assets/admin/pages/scripts/form-validation.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/admin/pages/scripts/components-form-tools.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/fuelux/js/spinner.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/jquery.input-ip-address-control-1.0.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/bootstrap-pwstrength/pwstrength-bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/jquery-tags-input/jquery.tagsinput.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/typeahead/handlebars.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/global/plugins/typeahead/typeahead.bundle.min.js" type="text/javascript"></script>
<script>
    jQuery(document).ready(function () {
        Metronic.init(); // init metronic core components
        Layout.init(); // init current layout
        QuickSidebar.init() // init quick sidebar
        TableEditable.init();
        ComponentsFormTools.init();
    });
</script>
<script>
    $(document).ready(function ($) {
        var list_target_id = 'list-target'; //first select list ID
        var list_select_id = 'list-select'; //second select list ID
        var initial_target_html = '<option value="">Please select a Category...</option>'; //Initial prompt for target select

        $('#' + list_target_id).html(initial_target_html); //Give the target select the prompt option

        $('#' + list_select_id).change(function (e) {

            //Grab the chosen value on first select list change
            var selectvalue = $(this).val();

            //Display 'loading' status in the target select list
            $('#' + list_target_id).html('<option value="">Loading...</option>');

            if (selectvalue == "") {
                //Display initial prompt in target select if blank value selected
                $('#' + list_target_id).html(initial_target_html);
            } else {
                //Make AJAX request, using the selected value as the GET

                $.ajax({url: '<?php echo $this->baseUrl(); ?>/Category/getsubcategory?id=' + selectvalue,
                    success: function (output) {
                        //alert(output);
                       
                        $('#' + list_target_id).html(output);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }});
            }
        });
    });
</script> 

<script type="text/javascript">
    $(function () {
        $(document).on('click', '.delbutton', function () {
//Save the link in a variable called element
            var element = $(this);
//Find the id of the link that was clicked
            var del_id = element.attr("id");
//Built a url to send
            var info = 'id=' + del_id;
            if (confirm("are you sure to delete this Product !?"))
            {
                $.ajax({
                    type: "GET",
                    url: "<?php echo $this->baseUrl(); ?>/Product/delproduct",
                    data: 'id=' + del_id,
                    success: function ()
                    {
                        window.location = "<?php echo $this->baseUrl(); ?>/Product";
                    }
                });
            }
            return false;
        });
    });
</script>



