
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/assets/js/jquery.simpletip-1.3.1.pack.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/demo.css" />

<style>
    div#page {
 
  width:100%;
  margin:0 auto;
  padding:5px;
  text-align:left;
}

div#header {
  border:2px solid red;
  width:750px;
  height:30px;
}
div#menu {
  
  
  float:left;
  margin:10px 0 10px 5px;
  height:350px;
}
div#content {
  
  width:500px;
  margin-left: 35%;
  margin-top: 1%;
  min-height:500px;
  _height:500px
}
div#footer {
  border:2px solid red;
  width:750px;
  height:30px;
}
</style>


<div id="page">

    <div id="menu">
        <div class="container" style="width:120%;" >

        <span class="top-label">
            <span class="label-txt" style="color:red;font-size: 15px;">Shopping Cart</span>
        </span>

            <div class="content-area"style="border: 2px solid black;">

            <div class="content drop-here " style="height: 510px;">

                <div id="cart-icon">
                    <img src="<?php echo $this->baseUrl(); ?>/img/Shoppingcart_128x128.png" alt="shopping cart" class="pngfix" width="100" height="60" />
                    <img src="img/ajax_load_2.gif" alt="loading.." id="ajax-loader" width="16" height="16" />
                </div>

                <form name="checkoutForm" method="post" action="<?php echo $this->baseUrl(); ?>/frontend/ordersubmit">
                     
                    <div id="item-list">
                    </div>
                    <div id="textarea" style="display: none;">
                       
                        <textarea style="height: 70px;width:90% ">Notes</textarea>
                    </div>
                </form>   
                
                <div class="clear"></div>

                <div id="total"></div>

       	        <div class="clear"></div>

                <a href="" style="height: 45px;" onclick="document.forms.checkoutForm.submit();
                        return false;" class="button">Checkout</a>

            </div>

        </div>

        <div class="bottom-container-border">
        </div>

    </div>
    </div>
    <div id="content">
        
        <div class="container" style="width:40%;" >

                    <span class="top-label">
                        <span class="label-txt" style="color:red;font-size: 15px;">Products</span>
                    </span>


                    <!-- END SALE PRODUCT & NEW ARRIVALS -->
                    <div class="content-area" style="width:45%;">

                        <div class="content drag-desired">


                            <?php
                            for ($i = 0; $i < count($this->products); $i++) {
                                echo '<div class="product"><img class="img-circle" value="'.$this->products[$i]['pro_id'].'" src="' . $this->baseUrl() . '/assets/img/product/' . $this->products[$i]['img'] . '" alt="' . htmlspecialchars($this->products[$i]['pro_name']) . '" width="128" height="128" class="pngfix" /></div>';
                            }
                            ?>





                            <div class="clear"></div>
                        </div>

                    </div>

                    <div class="bottom-container-border">
                    </div>

                </div>
    </div>

</div>

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/script.js"></script>
